### ISSUE TITLE
☢️Server crashes when I try to login

### ISSUE THREAD

**Issue by sbinlondon** [fac-15/to-you-to-me#34]
From the terminal

```
/Users/kate.beard/coding/to-you-to-me/src/handlers.js:111
  req.on("data", data => {
      ^

TypeError: req.on is not a function
    at loginData (/Users/kate.beard/coding/to-you-to-me/src/handlers.js:111:7)
    at Server.router (/Users/kate.beard/coding/to-you-to-me/src/router.js:32:5)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:677:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

So unfortunately will not be able to see the logged in functionality 😢

**Comment by sbinlondon** [comment]
Have a look at line 45 in the same file where there's a similar function that's running correctly 👁

**Comment by jcharnley** [comment]
all sorted thanks :)
